"use client";

import { useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Row = Record<string, string | number | boolean | null>;
type Filter = { field: string; operator: string; value: string | number | string[] };
type Metadata = { universe: number; universe_name: string; source_counts: Record<string, number>; industries: string[]; filters: string[]; built_at: string | null; market_as_of?: string | null; data_contract?: string[] };
type SortSpec = { field: string; direction: "asc" | "desc" };
type QueryResult = { rows?: Row[]; total?: number; page?: number; pages?: number; detail?: string };

const columns = ["Rank","Symbol","Company Name","Industry","Index","Momentum Score","CMP","3M Return","6M Return","3M Sharpe","6M Sharpe","R² 1Y","% From 52W High","% EMA 50","% EMA 200","Volume Ratio"];
const indexOptions = ["NIFTY 50","NIFTY NEXT 50","NIFTY MIDCAP 150","NIFTY SMALLCAP 250","NIFTY MICROCAP 250"];
function fmt(v: Row[keyof Row]) { if (v === null || v === undefined) return "—"; if (typeof v === "number") return v.toLocaleString("en-IN", {maximumFractionDigits:2}); return String(v); }
function pct(v: Row[keyof Row]) { return v == null ? "—" : `${Number(v) > 0 ? "+" : ""}${Number(v).toFixed(1)}%`; }

export default function Home() {
  const [rows,setRows] = useState<Row[]>([]), [total,setTotal] = useState(0), [pages,setPages] = useState(1), [metadata,setMetadata] = useState<Metadata | null>(null);
  const [filters,setFilters] = useState<Filter[]>([{field:"% From 52W High",operator:">=",value:-20},{field:"% EMA 200",operator:">",value:0},{field:"3M Return",operator:">",value:0}]);
  const [sort,setSort] = useState<SortSpec>({field:"Rank",direction:"asc"}), [page,setPage] = useState(1), [search,setSearch] = useState("");
  const [loading,setLoading] = useState(true), [error,setError] = useState(""), [degraded,setDegraded] = useState(false), [mobileFilter,setMobileFilter] = useState(false), [showColumns,setShowColumns] = useState(false), [visibleColumns,setVisibleColumns] = useState(columns), [saved,setSaved] = useState(false), [filterSearch,setFilterSearch] = useState("");

  useEffect(()=>{ const controller = new AbortController(); loadMetadata(controller.signal).catch(e=>{ if(!controller.signal.aborted){ setError(e instanceof Error ? e.message : "Unable to load screener metadata."); setDegraded(true); } }); return ()=>controller.abort(); },[]);
  useEffect(()=>{ const controller = new AbortController(); const timer=window.setTimeout(()=>runQuery(controller.signal),180); return ()=>{window.clearTimeout(timer);controller.abort();}; },[filters,sort,page,search]);
  useEffect(()=>{ try { const raw=localStorage.getItem("umiya_saved_screen"); if(raw){ const savedScreen=JSON.parse(raw); if(Array.isArray(savedScreen.filters)) setFilters(savedScreen.filters); if(savedScreen.sort?.field) setSort(savedScreen.sort); if(typeof savedScreen.search === "string") setSearch(savedScreen.search); } } catch { /* ignore malformed local state */ } },[]);
  async function loadMetadata(signal?: AbortSignal){ const r=await fetch(`${API}/api/v1/screener/metadata`,{cache:"no-store",signal}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.detail||"Screener dataset is unavailable."); if(signal?.aborted)return; setMetadata(data); setDegraded(false); }
  async function runQuery(signal?: AbortSignal){ setLoading(true); setError(""); try{ const r=await fetch(`${API}/api/v1/screener/query`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filters,sort,search:search.trim()||null,page,page_size:50}),signal}); const data:QueryResult=await r.json().catch(()=>({})); if(!r.ok) throw Object.assign(new Error(data.detail||"Screener request failed."),{status:r.status}); if(signal?.aborted)return; setRows(data.rows||[]);setTotal(data.total||0);setPages(data.pages||1);setDegraded(false); }catch(e){if(e instanceof DOMException && e.name==="AbortError")return;if(signal?.aborted)return;const status=typeof e==="object"&&e!==null&&"status" in e?Number((e as {status:number}).status):0;setRows([]);setTotal(0);setPages(1);setError(e instanceof Error?e.message:"Unable to load screener data.");setDegraded(status===503);}finally{if(!signal?.aborted)setLoading(false);} }
  function retry(){ const controller=new AbortController(); loadMetadata(controller.signal).catch(()=>{}); runQuery(controller.signal).catch(()=>{}); }
  function addFilter(f:Filter){setFilters(prev=>[...prev.filter(x=>x.field!==f.field),f]);setPage(1);setMobileFilter(false);setFilterSearch("")}
  function removeFilter(field:string){setFilters(prev=>prev.filter(f=>f.field!==field));setPage(1)}
  function doSort(field:string){setSort(prev=>({field,direction:prev.field===field&&prev.direction==="asc"?"desc":"asc"}));setPage(1)}
  function clearFilters(){setFilters([]);setPage(1)}
  function toggleColumn(c:string){setVisibleColumns(prev=>prev.includes(c)?prev.filter(x=>x!==c):[...prev,c])}
  function saveScreen(){localStorage.setItem("umiya_saved_screen",JSON.stringify({filters,sort,search}));setSaved(true);window.setTimeout(()=>setSaved(false),1800)}
  async function exportCsv(){setError("");try{const r=await fetch(`${API}/api/v1/screener/export`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({filters,sort,search:search.trim()||null,page:1,page_size:200})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||"Export failed.");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="umiya-screener.csv";a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Export failed.")}}
  const pageLabel=pages>1?`Page ${page} of ${pages}`:"All matching results", showingFrom=total===0?0:(page-1)*50+1, showingTo=Math.min(page*50,total);
  return <div className="shell">
    <aside className="side"><div className="logo"><span>U</span><div><b>Umiya</b><small>Momentum Research</small></div></div><nav><button className="active"><i>⌕</i>Screener</button></nav><div className="sidefoot">NSE 750<br/>Umiya Screener V2</div></aside>
    <main><header className="top"><div className="market"><div><small>DATASET</small><strong>{metadata?.universe_name||"NSE 750"}</strong></div><div><small>STOCKS</small><strong>{metadata?.universe??"—"}</strong></div><div className="desktop"><small>STATUS</small><strong className={!degraded&&metadata?"green":""}>{degraded?"DEGRADED":metadata?"READY":"—"}</strong></div><div className="desktop"><small>AS OF</small><strong>{metadata?.market_as_of||"—"}</strong></div></div><div className="topicons">API　↻　⚙</div></header>
      <section className="page">{error&&<div className={`alert ${degraded?"error":"warning"}`}><span>⚠ <b>{degraded?"Dataset unavailable":"Request failed"}</b> · {error}</span><button onClick={retry}>Retry</button></div>}
        <div className="heading"><div><h1>Screener</h1><p>NSE 750 multi-factor momentum ranking</p></div><div className="actions"><button onClick={saveScreen}>{saved?"✓ Saved":"▣ Save Screen"}</button><button onClick={()=>setMobileFilter(true)}>☰ Filters</button><button onClick={()=>setShowColumns(v=>!v)}>⚙ Columns</button></div></div>
        {showColumns&&<div className="columnpanel">{columns.map(c=><label key={c}><input type="checkbox" checked={visibleColumns.includes(c)} onChange={()=>toggleColumn(c)}/>{c}</label>)}</div>}
        <div className="filterbar"><button onClick={()=>setMobileFilter(true)}><b>Universe</b><span>NSE 750 · 5 indices</span></button><button onClick={()=>setMobileFilter(true)}><b>Price & Trend</b><span>{filters.filter(f=>f.field.includes("EMA")||f.field.includes("52W")).length} active</span></button><button onClick={()=>setMobileFilter(true)}><b>Momentum</b><span>{filters.filter(f=>f.field.includes("Return")||f.field.includes("Sharpe")||f.field.includes("Momentum")).length} active</span></button><button onClick={()=>setMobileFilter(true)}><b>Volatility</b><span>Available</span></button><button onClick={()=>setMobileFilter(true)}><b>Volume</b><span>{filters.some(f=>f.field.includes("Volume"))?"1 active":"Available"}</span></button><button onClick={()=>setMobileFilter(true)}><b>More Filters</b><span>{metadata?.filters.length??"—"} available</span></button></div>
        <div className="chips">{filters.map(f=><button key={f.field} onClick={()=>removeFilter(f.field)}>{f.field} {f.operator} {f.value}　×</button>)}{filters.length>0&&<button className="clear" onClick={clearFilters}>Clear all</button>}</div>
        <div className="kpis"><Kpi label="Universe" value={metadata?String(metadata.universe):"—"} sub="Live eligible universe"/><Kpi label="Filtered Results" value={loading?"…":String(total)} sub="Current screen"/><Kpi label="Industries" value={metadata?String(metadata.industries.length):"—"} sub="Classified"/><Kpi label="Data Status" value={degraded?"DEGRADED":metadata?"READY":"—"} sub={degraded?"Retry required":metadata?.built_at?"Precomputed dataset":"Waiting for dataset"} good={!!metadata&&!degraded}/></div>
        <div className="tablecard"><div className="tablehead"><div><b>Ranked Results</b><span> ({total})</span>{loading&&<span className="loading"> · updating…</span>}</div><div className="tools"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search stock or company…"/><button className="selected">▤ Table</button><button onClick={exportCsv} disabled={loading||degraded}>⇩ Export</button></div></div>
          {loading?<div className="empty"><b>Loading screener…</b><span>Fetching the precomputed analytical dataset.</span></div>:error&&degraded?<div className="empty"><b>Unable to load screener</b><span>{error}</span><button onClick={retry}>Retry</button></div>:rows.length===0?<div className="empty"><b>No stocks match this screen</b><span>Adjust or clear the active filters.</span></div>:<><div className="tablewrap"><table><thead><tr>{visibleColumns.map(c=><th key={c} onClick={()=>doSort(c)}>{c} <span>↕</span></th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.Symbol)}>{visibleColumns.map(c=><td key={c} className={c==="Symbol"?"symbol":""}>{c==="Symbol"?<a href={`/stocks/${encodeURIComponent(String(r.Symbol))}`}>{r[c]}</a>:c.includes("Return")||c.includes("EMA")||c==="% From 52W High"?pct(r[c]):c==="CMP"?`₹${fmt(r[c])}`:c==="Volume Ratio"?`${fmt(r[c])}x`:c==="Momentum Score"?<mark>{fmt(r[c])}</mark>:fmt(r[c])}</td>)}</tr>)}</tbody></table></div><div className="mobilecards">{rows.map((r,i)=><article key={String(r.Symbol)}><div className="rowtop"><span>#{r.Rank??showingFrom+i}　<a href={`/stocks/${encodeURIComponent(String(r.Symbol))}`}><b>{r.Symbol}</b></a></span><mark>{fmt(r["Momentum Score"])}</mark></div><div className="company">{r["Company Name"]} · {r.Industry} · {r.Index}</div><div className="metrics"><span>3M ROC<strong className="green">{pct(r["3M Return"])}</strong></span><span>6M ROC<strong className="green">{pct(r["6M Return"])}</strong></span><span>3M Sharpe<strong>{fmt(r["3M Sharpe"])}</strong></span><span>200 EMA<strong className="green">{pct(r["% EMA 200"])}</strong></span></div><div className="cardbottom">₹{fmt(r.CMP)} <a href={`/stocks/${encodeURIComponent(String(r.Symbol))}`}>› Full Analysis</a></div></article>)}</div><div className="pagination"><span>{showingFrom}–{showingTo} of {total} · {pageLabel}</span><div><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>← Previous</button><button disabled={page>=pages||loading} onClick={()=>setPage(p=>p+1)}>Next →</button></div></div></>}
        </div><footer>{metadata?.built_at?`Dataset built ${new Date(metadata.built_at).toLocaleString("en-IN")}:` : "No dataset loaded"} <span>● API-driven architecture</span></footer>
      </section></main>
    <nav className="bottomnav"><button className="active">⌕<small>Screener</small></button><button onClick={()=>setMobileFilter(true)}>☰<small>Filters</small></button><button onClick={()=>doSort("Rank")}>↕<small>Sort</small></button><button onClick={()=>setShowColumns(v=>!v)}>☷<small>Columns</small></button><button onClick={exportCsv}>⇩<small>Export</small></button></nav>
    {mobileFilter&&<div className="drawerback" onClick={()=>setMobileFilter(false)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerhead"><b>Filters</b><button onClick={()=>setMobileFilter(false)}>×</button></div><label>Search filters<input value={filterSearch} onChange={e=>setFilterSearch(e.target.value)} placeholder="Search…"/></label><div className="filteroptions"><div className="filtersection">Universe / Index</div>{indexOptions.filter(index=>index.toLowerCase().includes(filterSearch.toLowerCase())).map(index=><button key={index} onClick={()=>addFilter({field:"Index",operator:"=",value:index})}><b>{index}</b><small>Official NSE constituent set</small></button>)}<div className="filtersection">Price & Momentum</div>{[["Within 10% of 52W High",{"field":"% From 52W High",operator:">=",value:-10},"Price proximity"],["Above 200 EMA",{"field":"% EMA 200",operator:">",value:0},"Trend filter"],["3M Return > 10%",{"field":"3M Return",operator:">",value:10},"Momentum"],["3M Sharpe > 1",{"field":"3M Sharpe",operator:">",value:1},"Risk-adjusted momentum"]].filter(([label])=>String(label).toLowerCase().includes(filterSearch.toLowerCase())).map(([label,filter,desc])=><button key={String(label)} onClick={()=>addFilter(filter as Filter)}><b>{label as string}</b><small>{desc as string}</small></button>)}</div></div></div>}
  </div>
}
function Kpi({label,value,sub,good=false}:{label:string,value:string,sub:string,good?:boolean}){return <div className="kpi"><small>{label}</small><b className={good?"green":""}>{value}</b><span>{sub}</span></div>}
