"use client";

import { useEffect, useMemo, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
type Cell = string | number | boolean | null;
type Row = Record<string, Cell>;
type Filter = { field: string; operator: string; value: string | number | string[] };
type SortSpec = { field: string; direction: "asc" | "desc" };
type Metadata = { universe: number; universe_name: string; industries: string[]; filters: string[]; built_at: string | null; market_as_of?: string | null };
type QueryResult = { rows?: Row[]; total?: number; pages?: number; detail?: string };

const columns = [
  { field: "Rank", label: "Rank" }, { field: "Symbol", label: "Symbol" }, { field: "Company Name", label: "Company" },
  { field: "Industry", label: "Industry" }, { field: "Momentum Score", label: "Score" }, { field: "CMP", label: "CMP" },
  { field: "1M Return", label: "1M" }, { field: "3M Return", label: "3M" }, { field: "6M Return", label: "6M" },
  { field: "12M Return", label: "12M" }, { field: "6M Sharpe", label: "6M Sharpe" }, { field: "R² 1Y", label: "R²" },
  { field: "% From 52W High", label: "52W" }, { field: "% EMA 200", label: "EMA 200" }, { field: "Volume Ratio", label: "Vol x" },
];
const filterGroups = [
  { title: "Universe", fields: ["Index", "Industry", "Symbol"] },
  { title: "Momentum", fields: ["Momentum Score", "Acceleration", "1M Return", "3M Return", "6M Return", "9M Return", "12M Return", "3M Sharpe", "6M Sharpe", "R² 1Y", "Industry Relative"] },
  { title: "Trend", fields: ["CMP", "% From 52W High", "% EMA 50", "% EMA 100", "% EMA 200"] },
  { title: "Risk & Participation", fields: ["Persistence 6M %", "Volume Ratio"] },
  { title: "Data Quality", fields: ["Data Age Days"] },
];
const numericFields = new Set(filterGroups.flatMap((group) => group.fields).filter((field) => !["Index", "Industry", "Symbol"].includes(field)));
const selectFields = new Set(["Index", "Industry", "Symbol"]);
const defaultFilters: Filter[] = [
  { field: "% From 52W High", operator: ">=", value: -20 },
  { field: "% EMA 200", operator: ">", value: 0 },
  { field: "3M Return", operator: ">", value: 0 },
];
function fmt(value: Cell) { if (value === null || value === undefined) return "—"; if (typeof value === "number") return value.toLocaleString("en-IN", { maximumFractionDigits: 2 }); return String(value); }
function pct(value: Cell, digits = 1) { if (value === null || value === undefined || value === "") return "—"; const n = Number(value); if (!Number.isFinite(n)) return "—"; return `${n > 0 ? "+" : ""}${n.toFixed(digits)}%`; }
function isPositive(value: Cell) { return typeof value === "number" && value > 0; }
function isNegative(value: Cell) { return typeof value === "number" && value < 0; }
function displayCell(field: string, value: Cell) { if (field === "CMP") return value == null ? "—" : `₹${fmt(value)}`; if (field === "Volume Ratio") return value == null ? "—" : `${fmt(value)}x`; if (field.includes("Return") || field.includes("EMA") || field === "% From 52W High" || field === "Persistence 6M %") return pct(value); return fmt(value); }

export default function Home() {
  const [rows, setRows] = useState<Row[]>([]), [total, setTotal] = useState(0), [pages, setPages] = useState(1), [metadata, setMetadata] = useState<Metadata | null>(null);
  const [filters, setFilters] = useState<Filter[]>(defaultFilters), [sort, setSort] = useState<SortSpec>({ field: "Rank", direction: "asc" }), [page, setPage] = useState(1), [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [degraded, setDegraded] = useState(false), [filterOpen, setFilterOpen] = useState(false), [columnOpen, setColumnOpen] = useState(false), [saved, setSaved] = useState(false);
  const [filterSearch, setFilterSearch] = useState(""), [draftField, setDraftField] = useState("Momentum Score"), [draftOperator, setDraftOperator] = useState(">"), [draftValue, setDraftValue] = useState("");
  const [visibleColumns, setVisibleColumns] = useState(columns.map((column) => column.field));
  useEffect(() => { const controller = new AbortController(); loadMetadata(controller.signal).catch((e) => { if (!controller.signal.aborted) { setError(e instanceof Error ? e.message : "Unable to load screener metadata."); setDegraded(true); } }); return () => controller.abort(); }, []);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => runQuery(controller.signal), 140); return () => { window.clearTimeout(timer); controller.abort(); }; }, [filters, sort, page, search]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") setFilterOpen(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  async function loadMetadata(signal?: AbortSignal) { const response = await fetch(`${API}/api/v1/screener/metadata`, { cache: "no-store", signal }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Screener dataset is unavailable."); if (signal?.aborted) return; setMetadata(data); setDegraded(false); }
  async function runQuery(signal?: AbortSignal) { setLoading(true); setError(""); try { const response = await fetch(`${API}/api/v1/screener/query`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filters, sort, search: search.trim() || null, page, page_size: 50 }), signal }); const data: QueryResult = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(data.detail || "Screener request failed."), { status: response.status }); if (signal?.aborted) return; setRows(data.rows || []); setTotal(data.total || 0); setPages(data.pages || 1); setDegraded(false); } catch (e) { if (e instanceof DOMException && e.name === "AbortError") return; if (signal?.aborted) return; const status = typeof e === "object" && e !== null && "status" in e ? Number((e as { status: number }).status) : 0; setRows([]); setTotal(0); setPages(1); setError(e instanceof Error ? e.message : "Unable to load screener data."); setDegraded(status === 503); } finally { if (!signal?.aborted) setLoading(false); } }
  function retry() { const controller = new AbortController(); loadMetadata(controller.signal).catch(() => {}); runQuery(controller.signal).catch(() => {}); }
  function addFilter(filter: Filter) { setFilters((current) => [...current.filter((item) => item.field !== filter.field), filter]); setPage(1); }
  function removeFilter(field: string) { setFilters((current) => current.filter((filter) => filter.field !== field)); setPage(1); }
  function clearFilters() { setFilters([]); setPage(1); }
  function doSort(field: string) { setSort((current) => ({ field, direction: current.field === field && current.direction === "asc" ? "desc" : "asc" })); setPage(1); }
  function toggleColumn(field: string) { setVisibleColumns((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]); }
  function addDraftFilter() { if (!draftField || !draftValue.trim()) return; let value: string | number | string[] = draftValue.trim(); if (draftOperator === "in") value = draftValue.split(",").map((item) => item.trim()).filter(Boolean); else if (numericFields.has(draftField)) { const numeric = Number(draftValue); if (!Number.isFinite(numeric)) return; value = numeric; } addFilter({ field: draftField, operator: draftOperator, value }); }
  function saveScreen() { localStorage.setItem("umiya_saved_screen", JSON.stringify({ filters, sort, search })); setSaved(true); window.setTimeout(() => setSaved(false), 1600); }
  async function exportCsv() { setError(""); try { const response = await fetch(`${API}/api/v1/screener/export`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filters, sort, search: search.trim() || null, page: 1, page_size: 200 }) }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || "Export failed."); const blob = await response.blob(), url = URL.createObjectURL(blob), anchor = document.createElement("a"); anchor.href = url; anchor.download = "umiya-screener.csv"; anchor.click(); URL.revokeObjectURL(url); } catch (e) { setError(e instanceof Error ? e.message : "Export failed."); } }
  const filteredFields = useMemo(() => { const needle = filterSearch.trim().toLowerCase(); return filterGroups.map((group) => ({ ...group, fields: group.fields.filter((field) => !needle || field.toLowerCase().includes(needle)) })).filter((group) => group.fields.length); }, [filterSearch]);
  const pageFrom = total === 0 ? 0 : (page - 1) * 50 + 1, pageTo = Math.min(page * 50, total), activeCount = filters.length, shownColumns = columns.filter((column) => visibleColumns.includes(column.field));
  return <div className="shell"><main><section className="page">
    {error && <div className={`alert ${degraded ? "error" : "warning"}`}><span><b>{degraded ? "Dataset unavailable" : "Request issue"}</b> · {error}</span><button onClick={retry}>Retry</button></div>}
    <header className="screener-top"><div className="brandline"><div className="brandmark">U</div><div><b>Umiya</b><span>Screener</span></div></div><div className="dataset-meta"><span><b>{metadata?.universe_name || "NSE 750"}</b> universe</span><span>{metadata?.universe ?? "—"} eligible</span><span>As of {metadata?.market_as_of || "—"}</span><span className={degraded ? "negative" : metadata ? "positive" : ""}>{degraded ? "Degraded" : metadata ? "Live dataset" : "Loading"}</span></div><div className="top-actions"><button onClick={saveScreen}>{saved ? "✓ Saved" : "Save screen"}</button><button onClick={exportCsv} disabled={loading || degraded}>Export CSV</button></div></header>
    <section className="screen-title"><div><h1>Stock Screener</h1><p>Ranked NSE momentum research with server-side filtering, sorting and pagination.</p></div><div className="result-summary"><b>{loading ? "…" : total}</b><span>matching stocks</span></div></section>
    <section className="controlbar"><div className="searchbox"><span aria-hidden="true">⌕</span><input aria-label="Search stocks" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search symbol or company" />{search && <button className="clear-search" aria-label="Clear search" title="Clear search" onClick={() => { setSearch(""); setPage(1); }}>×</button>}</div><button className="filter-trigger" onClick={() => setFilterOpen(true)}>Filters <span>{activeCount}</span></button><button onClick={() => setColumnOpen((value) => !value)}>Columns</button><button className="sort-trigger" onClick={() => doSort(sort.field)}>Sort: {sort.field} {sort.direction === "asc" ? "↑" : "↓"}</button></section>
    {columnOpen && <div className="columnpanel">{columns.map((column) => <label key={column.field}><input type="checkbox" checked={visibleColumns.includes(column.field)} onChange={() => toggleColumn(column.field)} />{column.label}</label>)}</div>}
    <div className="activebar"><span><b>{activeCount}</b> active filter{activeCount === 1 ? "" : "s"}</span><div className="chips">{filters.map((filter) => <button key={filter.field} onClick={() => removeFilter(filter.field)} title={`Remove ${filter.field}`}>{filter.field} {filter.operator} {Array.isArray(filter.value) ? filter.value.join(", ") : filter.value} ×</button>)}{activeCount > 0 && <button className="clear-all" onClick={clearFilters}>Clear all</button>}</div></div>
    <section className="tablecard"><div className="tablehead"><div><b>Ranked results</b><span> · {metadata?.built_at ? `dataset ${new Date(metadata.built_at).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}` : "precomputed metrics"}</span></div>{loading && <span className="loading">Updating…</span>}</div>
      {loading ? <div className="empty"><b>Loading screener</b><span>Fetching prepared analytical data.</span></div> : error && degraded ? <div className="empty"><b>Unable to load the dataset</b><span>{error}</span><button onClick={retry}>Retry</button></div> : rows.length === 0 ? <div className="empty"><b>No stocks match these filters</b><span>Remove a filter or clear the screen to broaden the result set.</span><button onClick={clearFilters}>Clear filters</button></div> : <>
        <div className="tablewrap"><table><thead><tr>{shownColumns.map((column) => <th key={column.field} onClick={() => doSort(column.field)}>{column.label}<span>{sort.field === column.field ? (sort.direction === "asc" ? " ↑" : " ↓") : ""}</span></th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.Symbol)}>{shownColumns.map((column) => { const value = row[column.field], tone = column.field.includes("Return") || column.field.includes("EMA") || column.field === "% From 52W High" ? isPositive(value) ? "positive" : isNegative(value) ? "negative" : "" : ""; return <td key={column.field} className={column.field === "Symbol" ? "symbol" : tone}>{column.field === "Rank" ? <span className="rankbadge">{fmt(value)}</span> : column.field === "Symbol" ? <a href={`/stocks/${encodeURIComponent(String(value))}`}>{value}</a> : column.field === "Momentum Score" ? <strong className="scorecell">{fmt(value)}</strong> : displayCell(column.field, value)}</td>; })}</tr>)}</tbody></table></div>
        <div className="mobilecards">{rows.map((row, index) => <article key={String(row.Symbol)}><div className="mobile-row-top"><span className="mobile-rank">#{row.Rank ?? pageFrom + index}</span><a href={`/stocks/${encodeURIComponent(String(row.Symbol))}`}><b>{row.Symbol}</b></a><strong>{fmt(row["Momentum Score"])}</strong></div><div className="mobile-company">{row["Company Name"] || "—"} · {row.Industry || "—"}</div><div className="mobile-metrics"><span>1M <b className={isPositive(row["1M Return"]) ? "positive" : isNegative(row["1M Return"]) ? "negative" : ""}>{pct(row["1M Return"])}</b></span><span>3M <b className={isPositive(row["3M Return"]) ? "positive" : isNegative(row["3M Return"]) ? "negative" : ""}>{pct(row["3M Return"])}</b></span><span>6M <b className={isPositive(row["6M Return"]) ? "positive" : isNegative(row["6M Return"]) ? "negative" : ""}>{pct(row["6M Return"])}</b></span><span>EMA 200 <b>{pct(row["% EMA 200"])}</b></span></div><div className="mobile-bottom"><span>₹{fmt(row.CMP)}</span><a href={`/stocks/${encodeURIComponent(String(row.Symbol))}`}>Research →</a></div></article>)}</div>
        <div className="pagination"><span>{pageFrom}–{pageTo} of {total}</span><div><button disabled={page <= 1 || loading} onClick={() => setPage((value) => value - 1)}>← Prev</button><button disabled={page >= pages || loading} onClick={() => setPage((value) => value + 1)}>Next →</button></div></div>
      </>}
    </section><footer><span>Umiya Screener V2</span><span>Server-side quantitative engine · No frontend market-data calculations</span></footer>
  </section>
  {filterOpen && <div className="drawerback" onClick={() => setFilterOpen(false)}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Screener filters" onClick={(event) => event.stopPropagation()}><div className="drawerhead"><div><b>Filters</b><span>{activeCount} active · changes apply immediately</span></div><button onClick={() => setFilterOpen(false)} aria-label="Close filters">×</button></div><div className="drawer-search"><input aria-label="Find a filter" value={filterSearch} onChange={(event) => setFilterSearch(event.target.value)} placeholder="Find a metric…" />{filterSearch && <button onClick={() => setFilterSearch("")} aria-label="Clear filter search">×</button>}</div>
    <div className="quickfilters"><span>Quick screens</span><button onClick={() => addFilter({ field: "% EMA 200", operator: ">", value: 0 })}>Above 200 EMA</button><button onClick={() => addFilter({ field: "% From 52W High", operator: ">=", value: -10 })}>Within 10% of 52W high</button><button onClick={() => addFilter({ field: "3M Return", operator: ">", value: 10 })}>3M return &gt; 10%</button><button onClick={() => addFilter({ field: "6M Sharpe", operator: ">", value: 1 })}>6M Sharpe &gt; 1</button></div>
    <div className="filter-groups">{filteredFields.map((group) => <section key={group.title}><h3>{group.title}</h3><div className="filter-field-list">{group.fields.map((field) => <button key={field} onClick={() => { setDraftField(field); setDraftOperator(selectFields.has(field) ? "in" : ">"); setDraftValue(""); }}>{field}</button>)}</div></section>)}</div>
    <div className="custom-filter"><div><b>Add filter</b><span>Uses the prepared backend metric exactly as stored.</span></div><label>Metric<select value={draftField} onChange={(event) => { setDraftField(event.target.value); setDraftOperator(selectFields.has(event.target.value) ? "in" : ">"); }}><option value="">Choose metric</option>{filterGroups.flatMap((group) => group.fields).filter((field, index, all) => all.indexOf(field) === index).map((field) => <option key={field} value={field}>{field}</option>)}</select></label><label>Operator<select value={draftOperator} onChange={(event) => setDraftOperator(event.target.value)}>{(selectFields.has(draftField) ? ["in", "="] : [">", ">=", "<", "<=", "="]).map((operator) => <option key={operator}>{operator}</option>)}</select></label><label>Value<input value={draftValue} onChange={(event) => setDraftValue(event.target.value)} placeholder={draftOperator === "in" ? "Comma separated values" : "e.g. 10"} inputMode={numericFields.has(draftField) ? "decimal" : "text"} /></label><button className="apply-filter" onClick={addDraftFilter} disabled={!draftField || !draftValue.trim()}>Apply filter</button></div>
    <div className="drawer-actions"><button onClick={clearFilters}>Clear all</button><button className="primary" onClick={() => setFilterOpen(false)}>Done</button></div></aside></div>}
  </main><nav className="bottomnav"><button className="active" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>⌕<small>Screener</small></button><button onClick={() => setFilterOpen(true)}>☰<small>Filters {activeCount ? `(${activeCount})` : ""}</small></button><button onClick={() => doSort(sort.field)}>↕<small>Sort</small></button><button onClick={() => setColumnOpen((value) => !value)}>☷<small>Columns</small></button><button onClick={exportCsv}>⇩<small>Export</small></button></nav></div>;
}
