"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ChartRange } from "../../../components/chart-range";

type Row = Record<string, string | number | null>;
type ChartPoint = { date: string; adj_close: number; volume: number | null };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
function fmt(v: Row[keyof Row]) { return v == null ? "—" : typeof v === "number" ? v.toLocaleString("en-IN", { maximumFractionDigits: 2 }) : String(v); }
function pct(v: Row[keyof Row]) { return v == null ? "—" : `${Number(v) > 0 ? "+" : ""}${Number(v).toFixed(2)}%`; }
function tone(v: Row[keyof Row]) { return v == null ? "neutral" : Number(v) > 0 ? "positive" : Number(v) < 0 ? "negative" : "neutral"; }

export default function StockPage() {
  const params = useParams<{symbol:string}>(); const router = useRouter();
  const symbol = String(params.symbol || "").toUpperCase();
  const [stock,setStock] = useState<Row | null>(null); const [chart,setChart] = useState<ChartPoint[]>([]); const [days,setDays] = useState(252); const [error,setError] = useState("");
  useEffect(() => { if (!symbol) return; const controller=new AbortController(); setError(""); setStock(null); fetch(`${API}/api/v1/stocks/${encodeURIComponent(symbol)}`,{cache:"no-store",signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||"Stock unavailable");return r.json()}).then(data=>{if(!controller.signal.aborted)setStock(data)}).catch(e=>{if(e?.name!=="AbortError")setError(e instanceof Error?e.message:"Unable to load stock.")}); return()=>controller.abort()},[symbol]);
  useEffect(() => { if (!symbol) return; const controller=new AbortController(); setChart([]); fetch(`${API}/api/v1/stocks/${encodeURIComponent(symbol)}/chart?days=${days}`,{cache:"no-store",signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||"Chart unavailable");return r.json()}).then(c=>{if(!controller.signal.aborted)setChart(c.rows||[])}).catch(e=>{if(e?.name!=="AbortError")setError(e instanceof Error?e.message:"Unable to load chart.")}); return()=>controller.abort()},[symbol,days]);
  const values=useMemo(()=>chart.map(p=>p.adj_close).filter(Number.isFinite),[chart]); const min=values.length?Math.min(...values):0; const max=values.length?Math.max(...values):0; const path=values.length>1?values.map((v,i)=>`${(i/(values.length-1))*100},${100-((v-min)/(max-min||1))*92-4}`).join(" "):"";
  if(error&&!stock)return <main className="detailpage"><button className="back" onClick={()=>router.push("/")}>← Screener</button><div className="detailerror"><b>{error}</b><span>Return to the screener and try another symbol.</span></div></main>;
  if(!stock)return <main className="detailpage"><button className="back" onClick={()=>router.push("/")}>← Screener</button><div className="detailloading">Loading {symbol}…</div></main>;
  const momentum=Number(stock["Momentum Score"]); const rank=Number(stock.Rank); const trendPositive=Number(stock["% EMA 200"])>0;
  return <main className="detailpage">
    <div className="detailtopbar"><button className="back" onClick={()=>router.push("/")}>← Back to Screener</button><span>Stock Research · NSE 750</span></div>
    <header className="detailhero"><div className="heroidentity"><div className="stockbadge">{symbol.slice(0,2)}</div><div><div className="eyebrow">{stock.Industry||"NSE 750"} · {stock.Index||""}</div><h1>{symbol}</h1><p>{stock["Company Name"]||"—"}</p></div></div><div className="heroactions"><button onClick={()=>navigator.clipboard?.writeText(window.location.href)}>Copy link</button><button onClick={()=>router.push("/")}>Screen stocks</button></div></header>
    <section className="signalbar"><div className="signalprimary"><small>MOMENTUM RANK</small><strong>#{fmt(stock.Rank)}</strong><span>of NSE 750</span></div><div className="signalmetric"><small>MOMENTUM SCORE</small><strong>{fmt(stock["Momentum Score"])}</strong><span>Quantitative score</span></div><div className="signalmetric"><small>CURRENT PRICE</small><strong>₹{fmt(stock.CMP)}</strong><span>As of {fmt(stock["Market As Of"])}</span></div><div className="signalmetric"><small>1Y RETURN</small><strong className={tone(stock["12M Return"])}>{pct(stock["12M Return"])}</strong><span>12-month momentum</span></div><div className={`trendpill ${trendPositive?"up":"neutral"}`}><i></i>{trendPositive?"Above 200 EMA":"Below 200 EMA"}</div></section>
    <section className="detailgrid">
      <div className="detailcard chartcard featurecard"><div className="cardtitle"><div><b>Price Structure</b><span>Adjusted Close · {days===63?"3 months":days===126?"6 months":"1 year"} · {fmt(stock["Market As Of"])}</span></div><ChartRange value={days} onChange={setDays}/></div>{path?<div className="chart"><div className="chartgrid"><span></span><span></span><span></span><span></span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={path} fill="none" stroke="currentColor" strokeWidth="1.35" vectorEffect="non-scaling-stroke" /></svg></div>:<div className="chartempty">No chart data available for this range.</div>}<div className="chartlabels"><span>{chart[0]?.date?.slice(0,10)||"—"}</span><b>{values.length?`₹${values.at(-1)?.toLocaleString("en-IN",{maximumFractionDigits:2})}`:"—"}</b><span>{chart.at(-1)?.date?.slice(0,10)||"—"}</span></div></div>
      <div className="detailcard scorecard"><div className="cardtitle"><div><b>Momentum snapshot</b><span>How the stock ranks today</span></div><strong className="rankbig">#{rank||"—"}</strong></div><div className="scoreline"><span>Momentum Score</span><strong>{fmt(stock["Momentum Score"])}</strong></div><div className="scoretrack"><i style={{width:`${Math.max(0,Math.min(100,momentum||0))}%`}} /></div><div className="scorehint">Rank and score are supplied by the server-side quantitative engine.</div></div>
      <div className="detailcard widecard"><div className="cardtitle"><div><b>Momentum & Returns</b><span>Multi-horizon performance</span></div></div><div className="metricgrid six"><Metric label="1M" value={pct(stock["1M Return"])} tone={tone(stock["1M Return"])} /><Metric label="3M" value={pct(stock["3M Return"])} tone={tone(stock["3M Return"])} /><Metric label="6M" value={pct(stock["6M Return"])} tone={tone(stock["6M Return"])} /><Metric label="9M" value={pct(stock["9M Return"])} tone={tone(stock["9M Return"])} /><Metric label="12M" value={pct(stock["12M Return"])} tone={tone(stock["12M Return"])} /><Metric label="6M Sharpe" value={fmt(stock["6M Sharpe"])} /></div></div>
      <div className="detailcard widecard"><div className="cardtitle"><div><b>Technical Structure</b><span>Price relative to trend and risk characteristics</span></div></div><div className="metricgrid four"><Metric label="CMP" value={`₹${fmt(stock.CMP)}`} /><Metric label="From 52W High" value={pct(stock["% From 52W High"])} tone={tone(stock["% From 52W High"])} /><Metric label="EMA 50" value={pct(stock["% EMA 50"])} tone={tone(stock["% EMA 50"])} /><Metric label="EMA 100" value={pct(stock["% EMA 100"])} tone={tone(stock["% EMA 100"])} /><Metric label="EMA 200" value={pct(stock["% EMA 200"])} tone={tone(stock["% EMA 200"])} /><Metric label="R² 1Y" value={fmt(stock["R² 1Y"])} /><Metric label="Volume Ratio" value={`${fmt(stock["Volume Ratio"])}x`} /><Metric label="Persistence 6M" value={pct(stock["Persistence 6M %"])} tone={tone(stock["Persistence 6M %"])} /></div></div>
      <div className="detailcard contextcard"><div className="cardtitle"><div><b>Research context</b><span>Dataset & classification</span></div></div><dl className="context"><dt>Industry</dt><dd>{fmt(stock.Industry)}</dd><dt>Index</dt><dd>{fmt(stock.Index)}</dd><dt>Industry Relative</dt><dd>{fmt(stock["Industry Relative"])}</dd><dt>Acceleration</dt><dd>{fmt(stock.Acceleration)}</dd><dt>Data Age</dt><dd>{fmt(stock["Data Age Days"])} days</dd><dt>Market As Of</dt><dd>{fmt(stock["Market As Of"])}</dd></dl></div>
    </section><footer className="detailfooter"><span>Umiya Screener · Quantitative research interface</span><span>Data is precomputed server-side · No frontend financial calculations</span></footer>
  </main>
}
function Metric({label,value,tone="neutral"}:{label:string,value:string,tone?:string}) { return <div className="metric"><small>{label}</small><b className={tone}>{value}</b></div> }
