"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ChartRange } from "../../../components/chart-range";

type Cell = string | number | null;
type Row = Record<string, Cell>;
type ChartPoint = { date: string; adj_close: number; volume: number | null };
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
function fmt(value: Cell) { return value == null ? "—" : typeof value === "number" ? value.toLocaleString("en-IN", { maximumFractionDigits: 2 }) : String(value); }
function pct(value: Cell, digits = 2) { if (value == null) return "—"; const number = Number(value); return Number.isFinite(number) ? `${number > 0 ? "+" : ""}${number.toFixed(digits)}%` : "—"; }
function tone(value: Cell) { if (value == null) return "neutral"; const number = Number(value); return number > 0 ? "positive" : number < 0 ? "negative" : "neutral"; }

export default function StockPage() {
  const params = useParams<{ symbol: string }>(); const symbol = String(params.symbol || "").toUpperCase();
  const [stock, setStock] = useState<Row | null>(null), [chart, setChart] = useState<ChartPoint[]>([]), [days, setDays] = useState(252), [error, setError] = useState(""), [hoverIndex, setHoverIndex] = useState<number | null>(null);
  useEffect(() => { if (!symbol) return; const controller = new AbortController(); setError(""); setStock(null); fetch(`${API}/api/v1/stocks/${encodeURIComponent(symbol)}`, { cache: "no-store", signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || "Stock unavailable."); return response.json(); }).then((data) => { if (!controller.signal.aborted) setStock(data); }).catch((e) => { if (!(e && typeof e === "object" && "name" in e && e.name === "AbortError")) setError(e instanceof Error ? e.message : "Unable to load stock."); }); return () => controller.abort(); }, [symbol]);
  useEffect(() => { if (!symbol) return; const controller = new AbortController(); setChart([]); setHoverIndex(null); fetch(`${API}/api/v1/stocks/${encodeURIComponent(symbol)}/chart?days=${days}`, { cache: "no-store", signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || "Chart unavailable."); return response.json(); }).then((data) => { if (!controller.signal.aborted) setChart(data.rows || []); }).catch((e) => { if (!(e && typeof e === "object" && "name" in e && e.name === "AbortError")) setError(e instanceof Error ? e.message : "Unable to load chart."); }); return () => controller.abort(); }, [symbol, days]);
  const values = useMemo(() => chart.map((point) => Number(point.adj_close)).filter(Number.isFinite), [chart]); const min = values.length ? Math.min(...values) : 0; const max = values.length ? Math.max(...values) : 0; const points = values.length > 1 ? values.map((value, index) => `${(index / (values.length - 1)) * 100},${100 - ((value - min) / (max - min || 1)) * 88 - 6}`).join(" ") : ""; const selectedPoint = hoverIndex == null ? null : chart[hoverIndex];
  if (error && !stock) return <main className="detailpage"><button className="back" onClick={() => window.location.href = "/"}>← Screener</button><div className="detailerror"><b>{error}</b><span>Return to the screener and try another symbol.</span></div></main>;
  if (!stock) return <main className="detailpage"><button className="back" onClick={() => window.location.href = "/"}>← Screener</button><div className="detailloading">Loading {symbol}…</div></main>;
  const rank = Number(stock.Rank), trendPositive = Number(stock["% EMA 200"]) > 0;
  return <main className="detailpage">
    <div className="detailtopbar"><button className="back" onClick={() => window.location.href = "/"}>← Back to Screener</button><span>Stock Research · {stock.Industry || "NSE universe"}</span></div>
    <header className="detailhero"><div className="heroidentity"><div className="stockbadge">{symbol.slice(0, 2)}</div><div><div className="eyebrow">{stock.Industry || "NSE 750"} · {stock.Index || ""}</div><h1>{symbol}</h1><p>{stock["Company Name"] || "—"}</p></div></div><div className="heroactions"><button onClick={() => navigator.clipboard?.writeText(window.location.href)}>Copy link</button><button onClick={() => window.location.href = "/"}>Screen stocks</button></div></header>
    <section className="signalbar"><div className="signalprimary"><small>RANK</small><strong>#{fmt(stock.Rank)}</strong><span>of current eligible universe</span></div><div className="signalmetric"><small>MOMENTUM SCORE</small><strong>{fmt(stock["Momentum Score"])}</strong><span>server-side composite</span></div><div className="signalmetric"><small>CMP</small><strong>₹{fmt(stock.CMP)}</strong><span>market as of {fmt(stock["Market As Of"])}</span></div><div className="signalmetric"><small>12M RETURN</small><strong className={tone(stock["12M Return"])}>{pct(stock["12M Return"])}</strong><span>long-horizon momentum</span></div><div className={`trendpill ${trendPositive ? "up" : "down"}`}><i></i>{trendPositive ? "Above 200 EMA" : "Below 200 EMA"}</div></section>
    <section className="detailgrid">
      <div className="detailcard chartcard featurecard"><div className="cardtitle"><div><b>Price structure</b><span>Adjusted Close · {days === 63 ? "3 months" : days === 126 ? "6 months" : days === 252 ? "1 year" : "selected range"} · {fmt(stock["Market As Of"])}</span></div><ChartRange value={days} onChange={setDays} /></div>
        {points ? <div className="chart interactive-chart" onPointerLeave={() => setHoverIndex(null)}><div className="chartgrid"><span></span><span></span><span></span><span></span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" onPointerMove={(event) => { const rect = event.currentTarget.getBoundingClientRect(); const ratio = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); setHoverIndex(Math.round(ratio * (chart.length - 1))); }} aria-label="Adjusted close price chart"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="1.35" vectorEffect="non-scaling-stroke" />{hoverIndex != null && <circle cx={`${(hoverIndex / Math.max(1, chart.length - 1)) * 100}`} cy={`${100 - ((Number(chart[hoverIndex]?.adj_close) - min) / (max - min || 1)) * 88 - 6}`} r="1.6" fill="currentColor" vectorEffect="non-scaling-stroke" />}</svg>{selectedPoint && <div className="charttooltip"><b>₹{fmt(selectedPoint.adj_close)}</b><span>{selectedPoint.date.slice(0, 10)}</span></div>}</div> : <div className="chartempty">No chart data available for this range.</div>}
        <div className="chartlabels"><span>{chart[0]?.date?.slice(0, 10) || "—"}</span><b>{values.length ? `₹${values.at(-1)?.toLocaleString("en-IN", { maximumFractionDigits: 2 })}` : "—"}</b><span>{chart.at(-1)?.date?.slice(0, 10) || "—"}</span></div></div>
      <div className="detailcard scorecard"><div className="cardtitle"><div><b>Momentum snapshot</b><span>Why this stock ranks where it does</span></div><strong className="rankbig">#{rank || "—"}</strong></div><div className="scoreline"><span>Momentum Score</span><strong>{fmt(stock["Momentum Score"])}</strong></div><div className="scorehint">Composite score is supplied by the prepared quantitative dataset; no frontend ranking is performed.</div></div>
      <div className="detailcard widecard"><div className="cardtitle"><div><b>Momentum</b><span>Matched return horizons and risk-adjusted momentum</span></div></div><div className="metricgrid six"><Metric label="1M return" value={pct(stock["1M Return"])} tone={tone(stock["1M Return"])} /><Metric label="3M return" value={pct(stock["3M Return"])} tone={tone(stock["3M Return"])} /><Metric label="6M return" value={pct(stock["6M Return"])} tone={tone(stock["6M Return"])} /><Metric label="9M return" value={pct(stock["9M Return"])} tone={tone(stock["9M Return"])} /><Metric label="12M return" value={pct(stock["12M Return"])} tone={tone(stock["12M Return"])} /><Metric label="Acceleration" value={fmt(stock.Acceleration)} tone={tone(stock.Acceleration)} /></div></div>
      <div className="detailcard widecard"><div className="cardtitle"><div><b>Risk & trend</b><span>Prepared indicators available under the current Adj Close + Volume contract</span></div></div><div className="metricgrid six"><Metric label="3M Sharpe" value={fmt(stock["3M Sharpe"])} /><Metric label="6M Sharpe" value={fmt(stock["6M Sharpe"])} /><Metric label="R² 1Y" value={fmt(stock["R² 1Y"])} /><Metric label="From 52W high" value={pct(stock["% From 52W High"])} tone={tone(stock["% From 52W High"])} /><Metric label="EMA 200" value={pct(stock["% EMA 200"])} tone={tone(stock["% EMA 200"])} /><Metric label="Volume ratio" value={stock["Volume Ratio"] == null ? "—" : `${fmt(stock["Volume Ratio"])}x`} /></div></div>
      <div className="detailcard widecard"><div className="cardtitle"><div><b>Relative & data context</b><span>Classification, industry-relative strength and dataset provenance</span></div></div><div className="contextgrid"><Metric label="Industry" value={fmt(stock.Industry)} /><Metric label="Index" value={fmt(stock.Index)} /><Metric label="Industry relative" value={fmt(stock["Industry Relative"])} tone={tone(stock["Industry Relative"])} /><Metric label="Persistence 6M" value={pct(stock["Persistence 6M %"])} tone={tone(stock["Persistence 6M %"])} /><Metric label="Data age" value={stock["Data Age Days"] == null ? "—" : `${fmt(stock["Data Age Days"])} days`} /><Metric label="Market as of" value={fmt(stock["Market As Of"])} /></div></div>
    </section><footer className="detailfooter"><span>Umiya Screener V2 · quantitative research interface</span><span>Prepared server-side · Adj Close + Volume data contract</span></footer>
  </main>;
}
function Metric({ label, value, tone = "neutral" }: { label: string; value: string; tone?: string }) { return <div className="metric"><small>{label}</small><b className={tone}>{value}</b></div>; }
